services:
  stat_tracker_server:
    build: .
    ports:
      - "4031:4031"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - .:/app
      - /app/__pycache__
      - ./data:/app/data
    restart: unless-stopped
